color = { 'red', 'green', 'blue'}
print(color)
color.add('red')
print(color)
color.add('grey')
print(color)
color.remove('red')
print(color)
color.discard('red')
print(color)
color.clear()
print(color)